### ISSUE TITLE
Add user registry API

### ISSUE THREAD

**Issue by dockerymick** [agstack/agstack-website#15]
## Create an informative issue (See each section)

Using the current website as a model, please complete the issue template. 

### Prerequisite: Start with what we have

Always look at the current website to describe the change that is needed. Use the following link: 

**[AgStack website](https://agstack.github.io/agstack-website/)**

Add the User registry API documentation and JSON file (format in OpenAPI). Formatting the API in OpenAPI format will make the API interactive. **Update the following file: https://github.com/agstack/agstack-website/blob/main/apis/user_registry.json**

<img width="1583" alt="Screen Shot 2023-01-27 at 2 57 19 PM" src="https://user-images.githubusercontent.com/60616885/215185431-fb611d6a-8131-4bb8-b28b-956567c24162.png">

### Describe the changes in the doc and link to your dev story

Provide info for the following steps:

1. - [x] **Mandatory** Choose the page that needs to be updated:
     
      - [ ] About
      - [ ] Contribute
      - [x] Projects (User registry) 
      - [x] APIs
      - [ ] Resources
      - [ ] Glossary
      - [ ] New topic

2. - [ ] **Mandatory for bugs:** Clearly define what the problem is, what the change is, and link to the page:

3. - [ ] **Mandatory for content:**
            
       - [ ] Add steps and/or other important conceptual information here: 
       - [ ] Add verification at the end of the task, how does the user verify success (a command to run or a result to see?)
       - [ ] Add link to related dev story, if applicable

**Comment by dockerymick** [comment]
@kiafaldorius Will you also help with formatting this API as well? Here is the Juptyer file that @Aanish97 provided to me; I attempted to use the Swagger editor to convert the file, but didn't see an option to convert `.ipynb` files.:

```
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "7e4260f7",
   "metadata": {},
   "source": [
    "# User - Asset Registry"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "24e78804",
   "metadata": {},
   "source": [
    "### imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "bf2e1318",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ae42dc14",
   "metadata": {},
   "source": [
    "### Web app deployed URLs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "998b8727",
   "metadata": {},
   "outputs": [],
   "source": [
    "asset_registry_base = \"http://143.198.58.1\"\n",
    "user_registry_base = \"http://138.197.50.41\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f245433b",
   "metadata": {},
   "source": [
    "### User Registry signup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "id": "f78e6205",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<Response [200]>\n"
     ]
    }
   ],
   "source": [
    "req_body = {'email': 'test@test.com', 'phone_num': '011112223333', 'password': 'Asdf1234', 'confirm_pass': 'Abcd@1234', 'discoverable': \n",
    "            True}\n",
    "res = requests.post(user_registry_base + \"/signup\", json=req_body)\n",
    "print(res)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "de93314d",
   "metadata": {},
   "source": [
    "#### Blacklisted email cannot be registered"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "id": "3c2db7d5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'message': 'This email is blacklisted'}\n"
     ]
    }
   ],
   "source": [
    "# shouldn't be allowed to register since it is blacklisted\n",
    "req_body = {'email': 'fishy@fishy.com', 'phone_num': '011112223333', 'password': 'Asdf1234', 'confirm_pass': 'Asdf1234', 'discoverable': \n",
    "            True}\n",
    "res = requests.post(user_registry_base + \"/signup\", json=req_body)\n",
    "print(res.json())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "616048e6",
   "metadata": {},
   "source": [
    "#### Sign up with valid email"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "9b385fe6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'message': 'A user with this email already exists'}\n"
     ]
    }
   ],
   "source": [
    "req_body = {'email': 'test4@test.com', 'phone_num': '011112223333', 'password': 'Asdf1234', 'confirm_pass': 'Asdf1234', 'discoverable': \n",
    "            True}\n",
    "res = requests.post(user_registry_base + \"/signup\", json=req_body)\n",
    "print(res.json())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "97a189e0",
   "metadata": {},
   "source": [
    "#### Fetching the JWT token"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "a8963ca9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDY4ODE1NiwianRpIjoiNDhlYTU3ZDgtZGI1YS00YzlkLTkwYjYtZTEyOWE4YWNjMDhjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjc0Njg4MTU2LCJleHAiOjE2NzQ3MDI1NTYsImRvbWFpbiI6ImdtYWlsLmNvbSJ9.YvlNuGklWpXps6v_8B4iAuh1fWZvflS5D9UhbAg1EW8', 'refresh_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDY4ODE1NiwianRpIjoiNTQxNTFjZDYtYjY1My00ODJiLWI0ZmMtNzRhNjBmMjc4ZDdlIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOjQsIm5iZiI6MTY3NDY4ODE1NiwiZXhwIjoxNjc0Nzc0NTU2fQ.RyEb_GZbfbVh6PDOMO0xnHLmCBXjiaCgW0iDvmZfkzY'}\n"
     ]
    }
   ],
   "source": [
    "# this endpoint returns tokens if the given user is registered\n",
    "req_body = {'email': 'aanish@gmail.com', 'password': 'Helloesk!2'}\n",
    "res = requests.post(user_registry_base, json=req_body)\n",
    "print(res.json())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "09252a5a",
   "metadata": {},
   "source": [
    "#### Incorrect password"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "ae669ab4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'message': 'Incorrect Password!'}\n"
     ]
    }
   ],
   "source": [
    "# incorrect password\n",
    "req_body = {'email': 'test@test.com', 'password': 'incorrect'}\n",
    "res = requests.post(user_registry_base, json=req_body)\n",
    "print(res.json())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "39045628",
   "metadata": {},
   "source": [
    "### Access token and Refresh token"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "12af8585",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDY4ODE1OCwianRpIjoiZTBmMmUxMjYtYjU2OC00YzQ4LTg0MzktYmZhNjdiY2I1OWViIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjc0Njg4MTU4LCJleHAiOjE2NzQ3MDI1NTgsImRvbWFpbiI6ImdtYWlsLmNvbSJ9.Q1sazt8E_t1qOwMp2E_cVj574e_p14r-dxbqbUaMrIM', 'refresh_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDY4ODE1OCwianRpIjoiNTdiNTFmZDItNzcwMS00OWJkLWIzNmUtZGYzNmEzZjRhZTIzIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOjQsIm5iZiI6MTY3NDY4ODE1OCwiZXhwIjoxNjc0Nzc0NTU4fQ.whzY03Qy7WPUq7rn4CPebnmPbZkP1Y8aXNrNZ7ruDOI'}\n"
     ]
    }
   ],
   "source": [
    "# tokens\n",
    "req_body = {'email': 'aanish@gmail.com', 'password': 'Helloesk!2'}\n",
    "res = requests.post(user_registry_base, json=req_body)\n",
    "token = res.json()['access_token']\n",
    "print(res.json())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "174368b7",
   "metadata": {},
   "source": [
    "### Creating the session"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "70ace363",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<RequestsCookieJar[<Cookie access_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDY4ODE1OSwianRpIjoiMzRhNGU0MWEtYTY5Mi00YzE1LTg2ZDYtNGQxZDQxNTM1ODNmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjc0Njg4MTU5LCJleHAiOjE2NzQ3MDI1NTksImRvbWFpbiI6ImdtYWlsLmNvbSJ9.wDNrY4PrT5xK6bckfq9WyeRwkhphnagHK-RRODRS980 for 138.197.50.41/>, <Cookie refresh_token_cookie=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDY4ODE1OSwianRpIjoiMjBkZWEwNmUtYWI2NS00Y2NmLTkxMzMtOWY4MDAzOTM2Y2IxIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOjQsIm5iZiI6MTY3NDY4ODE1OSwiZXhwIjoxNjc0Nzc0NTU5fQ.dmSzm-WcqR1pBrQ5dqHaLPWFiUfXULakVh5p9zCTKNs for 138.197.50.41/>]>\n",
      "Cookies have been set successfully!\n"
     ]
    }
   ],
   "source": [
    "# using session to store cookies that are persistent\n",
    "session = requests.session()\n",
    "session.headers = headers = {\n",
    "    'Accept': 'application/json',\n",
    "    'Content-Type': 'application/json'\n",
    "}\n",
    "req_body = {'email': 'aanish@gmail.com', 'password': 'Helloesk!2'}\n",
    "res = session.post(user_registry_base, json=req_body)\n",
    "print(session.cookies)\n",
    "if res.status_code == 200:\n",
    "    print(\"Cookies have been set successfully!\")\n",
    "else:\n",
    "    print(\"An error occurred while setting the cookies.\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "52130716",
   "metadata": {},
   "source": [
    "### Update the phone number"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "ccbf4dfa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'message': 'Nothing to be updated'}\n"
     ]
    }
   ],
   "source": [
    "# updating the phone number\n",
    "req_body = {'phone_num': '123500919', 'discoverable': 'false'}\n",
    "res = requests.post(user_registry_base + \"/update\", json=req_body, cookies=session.cookies)\n",
    "print(res.json())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3dade7ce",
   "metadata": {},
   "source": [
    "### Sending token from User registry to Asset registry"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "40943cad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<Response [200]>\n"
     ]
    }
   ],
   "source": [
    "# sending tokens from user-registry to asset-registry base url\n",
    "tokenAuth = \"Bearer \" + token\n",
    "session.headers = headers = {\n",
    "    'Authorization': tokenAuth\n",
    "}\n",
    "res = session.get(user_registry_base + \"/asset-registry-home\", cookies=session.cookies)\n",
    "print(res)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c148b4ed",
   "metadata": {},
   "source": [
    "#### Protected means a private route, requires login\n",
    "#### Public routes donot require login"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7080c627",
   "metadata": {},
   "source": [
    "### Register a Field Boundary (protected)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "132daf88",
   "metadata": {},
   "source": [
    "#### Register first field"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "id": "3ebd4977",
   "metadata": {}
```

@Aanish97 can you both work together on converting this information? [OpenAPI Guidance - Basic structure](https://swagger.io/docs/specification/basic-structure/). I appreciate the help!

**Comment by dockerymick** [comment]
Recently enabled the `Topbar` function to select the API from a drop-down menu

**Comment by dockerymick** [comment]
CC: @sumerjohal

**Comment by dockerymick** [comment]
New files provided by @Aanish97 
**User registry API**:
{
	"info": {
		"_postman_id": "e6a777b8-a36d-493e-ba4b-35651d38b55f",
		"name": "user-registry",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "15370791"
	},
	"item": [
		{
			"name": "Signup",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "email",
							"value": "asdf@asdf.com",
							"type": "text"
						},
						{
							"key": "phone_num",
							"value": "03123948566",
							"type": "text"
						},
						{
							"key": "password",
							"value": "Asdf1234",
							"type": "text"
						},
						{
							"key": "confirm_pass",
							"value": "Asdf1234",
							"type": "text"
						},
						{
							"key": "newsletter",
							"value": "checked",
							"type": "text"
						},
						{
							"key": "discoverable",
							"value": "checked",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "{{base_url}}/signup",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"signup"
					]
				}
			},
			"response": []
		},
		{
			"name": "Login",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "email",
							"value": "test@test.com",
							"type": "text"
						},
						{
							"key": "password",
							"value": "Asdf1234",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "{{base_url}}",
					"host": [
						"{{base_url}}"
					]
				}
			},
			"response": []
		},
		{
			"name": "Update User",
			"request": {
				"method": "PATCH",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n\t\"phone_num\": \"7997\"\n}"
				},
				"url": {
					"raw": "{{base_url}}/user",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"user"
					]
				}
			},
			"response": []
		},
		{
			"name": "Logout",
			"request": {
				"method": "DELETE",
				"header": [],
				"url": {
					"raw": "{{base_url}}/logout",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"logout"
					]
				}
			},
			"response": []
		},
		{
			"name": "Refresh token",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{base_url}}/refresh",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"refresh"
					]
				}
			},
			"response": []
		},
		{
			"name": "Get all Domains",
			"request": {
				"method": "GET",
				"header": []
			},
			"response": []
		},
		{
			"name": "Get Authority Token for a Domain",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{base_url}}/authority-token/?domain=test.com",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"authority-token",
						""
					],
					"query": [
						{
							"key": "domain",
							"value": "test.com"
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "New Request",
			"request": {
				"method": "GET",
				"header": []
			},
			"response": []
		}
	],
	"variable": [
		{
			"key": "base_url",
			"value": "http://127.0.0.1:5000"
		}
	]
}




**Asset registry API**:

{
	"info": {
		"_postman_id": "c48869dc-05d4-4444-9a5b-f6071c9237b8",
		"name": "Asset Registry",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "15370791"
	},
	"item": [
		{
			"name": "Fetch a Field (public)",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{base_url}}/fetch-field/89d864f50bb864fb79fb5672f51da53991bc92e12c61f9222d5e35cd5ad52c0c?s2_index=1,2,3,4,5,6,7,8,9,10,11,12,13",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"fetch-field",
						"89d864f50bb864fb79fb5672f51da53991bc92e12c61f9222d5e35cd5ad52c0c"
					],
					"query": [
						{
							"key": "s2_index",
							"value": "1,2,3,4,5,6,7,8,9,10,11,12,13"
						}
					]
				}
			},
			"response": []
		},
		{
			"name": "Fetch a Field WKT (public)",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{base_url}}/fetch-field-wkt/752731c512e0fcb3bd7472cb2b89cdee859eefa6b0c34713e2050b109c2845ee",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"fetch-field-wkt",
						"752731c512e0fcb3bd7472cb2b89cdee859eefa6b0c34713e2050b109c2845ee"
					]
				}
			},
			"response": []
		},
		{
			"name": "Home (private)",
			"request": {
				"auth": {
					"type": "bearer",
					"bearer": [
						{
							"key": "token",
							"value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDE4NTQ5MywianRpIjoiZjU2ZmJiMzctMDBkYi00ODc4LTk3NTktNGRkZWU2ODE5YThkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NSwibmJmIjoxNjc0MTg1NDkzLCJleHAiOjE2NzQxOTk4OTMsImRvbWFpbiI6InRlc3QuY29tIn0.JKeJXFeLOfUXKuGsMvWZCAiXdkeXn2lb8txAO-mBEVU",
							"type": "string"
						}
					]
				},
				"method": "POST",
				"header": [
					{
						"key": "Authorization",
						"value": "Bearer",
						"description": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3NDE4NTQ5MywianRpIjoiZjU2ZmJiMzctMDBkYi00ODc4LTk3NTktNGRkZWU2ODE5YThkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NSwibmJmIjoxNjc0MTg1NDkzLCJleHAiOjE2NzQxOTk4OTMsImRvbWFpbiI6InRlc3QuY29tIn0.JKeJXFeLOfUXKuGsMvWZCAiXdkeXn2lb8txAO-mBEVU",
						"type": "text"
					}
				],
				"url": {
					"raw": "{{base_url}}",
					"host": [
						"{{base_url}}"
					]
				}
			},
			"response": []
		},
		{
			"name": "Register a Field Boundary (private)",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"value": "application/json",
						"type": "text",
						"disabled": true
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"wkt\": \"POLYGON ((-93.69805256358295 41.9757745318825, -93.69249086165937 41.97576056598778, -93.69245431117128 41.96883250535657, -93.69804142643369 41.97220658289061, -93.69805256358295 41.9757745318825))\",\n    \"s2_index\": \"8,13\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "{{base_url}}/register-field-boundary",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"register-field-boundary"
					]
				}
			},
			"response": []
		},
		{
			"name": "Fetch Overlapping Fields (private)",
			"protocolProfileBehavior": {
				"disableBodyPruning": true
			},
			"request": {
				"method": "GET",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"wkt\": \"POLYGON((74.373885630991 31.47708528231105,74.37425041141702 31.476426474392063,74.37634253444864 31.47703038182828,74.37715792598917 31.477405534485314,74.3768575185795 31.478055185529357,74.373885630991 31.47708528231105))\",\n    \"resolution_level\": 13,\n    \"threshold\": 40,\n    \"domain\": \"\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "{{base_url}}/fetch-overlapping-fields",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"fetch-overlapping-fields"
					]
				}
			},
			"response": []
		},
		{
			"name": "Fetch Fields for a Point (private)",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"latitude\": 31.476859704055347,\n    \"longitude\": 74.37447591413982,\n    \"s2_index\": \"8,15\"\n}\n",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "{{base_url}}/fetch-fields-for-a-point",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"fetch-fields-for-a-point"
					]
				}
			},
			"response": []
		},
		{
			"name": "Get Percentage Overlap of two Geo Ids (public)",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"geo_id_field_1\": \"7af4d1ddb9fb20e5cfe4544afab435c74e82a76024c1b8abaf9dd33163fc984b\",\n    \"geo_id_field_2\": \"7b02942a48b934ed20854e9e4339be84c241c0b2770739b65c334649921a48ca\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "{{base_url}}/get-percentage-overlap-two-fields",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"get-percentage-overlap-two-fields"
					]
				}
			},
			"response": []
		},
		{
			"name": "Fetch Bounding box Fields (private)",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "{\n    \"latitudes\": \"31.477779423633137 31.478602920901388 31.474320655972566 31.47543699178076\",\n    \"longitudes\": \"74.3729835582561 74.38032208212084 74.37404571302599 74.38112674482531\",\n    \"s2_index\": \"8,15\"\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "{{base_url}}/fetch-bounding-box-fields",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"fetch-bounding-box-fields"
					]
				}
			},
			"response": []
		},
		{
			"name": "Logout (private)",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{base_url}}/logout",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"logout"
					]
				}
			},
			"response": []
		},
		{
			"name": "Get all Domains (public)",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{base_url}}/domains",
					"host": [
						"{{base_url}}"
					],
					"path": [
						"domains"
					]
				}
			},
			"response": []
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "base_url",
			"value": "http://127.0.0.1:5000"
		}
	]
}

**Comment by dockerymick** [comment]
Add Hamza to this repository : MHA10

**Comment by kiafaldorius** [comment]
I'll take a look at this later this week, maybe over the weekend.

**Comment by dockerymick** [comment]
@kiafaldorius we have updated JSON for the user registry 


```
{
    "openapi": "3.0.3",
    "servers": [
        {
            "url": "http://138.197.50.41",
            "description": "Production Server (live data)"
        }
    ],
    "info": {
        "title": "user-registry",
        "version": "1.0.0",
        "contact": {}
    },
    "paths": {
        "/signup": {
            "post": {
                "summary": "Signup",
                "description": "Signup a user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "confirm_pass": {
                                        "type": "string",
                                        "example": "Asdf1234"
                                    },
                                    "discoverable": {
                                        "type": "boolean",
                                        "example": True
                                    },
                                    "email": {
                                        "type": "string",
                                        "example": "asdf@asdf.com"
                                    },
                                    "newsletter": {
                                        "type": "string",
                                        "example": "checked"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "Asdf1234"
                                    },
                                    "phone_num": {
                                        "type": "string",
                                        "example": "03123948566"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Signed up"
                    }
                }
            }
        },
        "/": {
            "post": {
                "summary": "Login",
                "description": "Login in the User Registry",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "example": "test@test.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "Asdf1234"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": The access token and refresh token
                    }
                }
            }
        },
        "/update": {
            "patch": {
                "summary": "Update User",
                "description": "Update User",
                "operationId": "updateUser",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "phone_num": {
                                        "type": "string",
                                        "example": "7997"
                                    }
                                }
                            },
                            "example": {
                                "phone_num": "7997"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Phone number updated"
                    }
                }
            }
        },
        "/logout": {
            "delete": {
                "summary": "Logout",
                "description": "Logout of the User Registry",
                "operationId": "logout",
                "responses": {
                    "200": {
                        "description": "Logged out successfully."
                    }
                }
            }
        },
        "/authority-token/": {
            "get": {
                "summary": "Get Authority Token for a Domain",
                "description": "Get Authority Token for a Domain",
                "parameters": [
                    {
                        "name": "domain",
                        "in": "query",
                        "schema": {
                            "type": "string",
                            "example": "test.com"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": The authority token for the Domain
                    },
                    "404": {
                        "description": "Authority token not found"
                    }
                }
            }
        }
    },
    "tags": []
}
```

Adding this to the repository for now and will continue to make updates for this

**Comment by dockerymick** [comment]
Progress! @MHA10 Thanks for making the changes! I see that there is a label that say "INVALID" at the end of the API page @kiafaldorius will you check why the label is appearing ([user-registry.json](https://github.com/agstack/agstack-website/blob/main/apis/user_registry.json))? 


 we should also add a brief description stating the purpose for the API. Similar to what we have in the Asset registry 
<img width="1496" alt="Screen Shot 2023-02-03 at 10 14 03 AM" src="https://user-images.githubusercontent.com/60616885/216638913-8293aafc-8357-4eaf-9cb8-3151d4176206.png">

**Comment by dockerymick** [comment]
The API is valid now: https://agstack.github.io/agstack-website/user_registry_api?urls.primaryName=User%20registry

@Aanish97 @sumerjohal i imagine we will improve the Swagger API doc, by revising the descriptions of the endpoints. From my perspective, this issue can be closed. If there are requests for the User registry, please create a [AgStack website issue](https://github.com/agstack/agstack-website/issues/new?assignees=&labels=website&template=website_issue.md).
